// Copyright 2017-2021 Closed Sum Games, LLC. All Rights Reserved.
#include "Types/CsTypes_Primitive.h"

// MemberType
#pragma region

namespace NCsMemberType
{
	CSCORE_API CS_CREATE_ENUM_STRUCT(Bool);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Uint8);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Int32);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Enum);
	CSCORE_API CS_CREATE_ENUM_STRUCT(EnumClass);
	CSCORE_API CS_CREATE_ENUM_STRUCT(EnumNamespaced);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Float);
	CSCORE_API CS_CREATE_ENUM_STRUCT(String);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Name);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Vector);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Rotator);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Color);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Object);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Actor);
	CSCORE_API CS_CREATE_ENUM_STRUCT(Pawn);
	CSCORE_API CS_CREATE_ENUM_STRUCT(ActorComponent);
	CSCORE_API CS_CREATE_ENUM_STRUCT(SceneComponent);
	CSCORE_API CS_CREATE_ENUM_STRUCT(PrimitiveComponent);
	CSCORE_API CS_CREATE_ENUM_STRUCT(StaticMeshComponent);
	CSCORE_API CS_CREATE_ENUM_STRUCT(SkeletalMeshComponent);
}

#pragma endregion MemberType